### ISSUE TITLE
Licensing of protocol implementations (MDP, TSP, PPP, etc.) 

### ISSUE THREAD

**Issue by karmalis** [zeromq/rfc#179]
Good day,

I am aware that a similar issue (https://github.com/zeromq/rfc/issues/133) was answered in regards to actual library or language implementations, however it looks a little confusing when it comes to actual specific protocol implementations.

Case: 
In our company, we want to use the Majordomo protocol which we will write our own implementation using the libzmq alongside following the specification defined on https://rfc.zeromq.org/spec/7 . The implementation will be used for "Software as a Service" product.

Issue:
The specification states, that the license of it (the specification, so presuming it goes the same for the protocol itself) is GPLv3.
When we look at https://github.com/zeromq/majordomo , which is an example guide reference implementation, it is licensed under MPL 2. There is a "sub implementation" in C (not C++), underneath the same project https://github.com/zeromq/majordomo/tree/master/libmdp which seems to be licensed under GPLv3. The example defined in the specification https://github.com/shykes/pyzmq-mdp is also licensed under GPLv3.

Now we understand that both ZeroMQ as well as any related projects are now slowly turning towards to be licensed under MPL 2 (ref: discussion on https://github.com/zeromq/majordomo/issues/64 ).

The question is: 
If we write our own implementation of Majordomo pattern (or any other pattern in this recard) how should we license it? Would we have the consent in this particular case to not license our implementation under GPLv3? Could you advise on how to best to approach this?

Many thanks

**Comment by bluca** [comment]
If you do a clean-room reimplementation, using only the protocol RFCs as documentation and without looking at the reference implementation, then you are free to license it however you like.

If you look at the reference implementation as a guide or even copy code from it, then in most jurisdiction it would be classified as a derivative work, so you have to follow the original license. Usual "I Am Not A Lawyer" disclaimer.

Regarding the protocol's license, it's licensed this way so that if you do incompatible changes you have to publish them (eg: add new fields or change existing ones). It does not affect the license of the implementation.

**Comment by karmalis** [comment]
This makes perfect sense. Thank you for clarifying.
